language: java

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t zerko/tp-cpe-travis:http-api-server sample-application-http-api-server
  - docker build -t zerko/tp-cpe-travis:db-changelog sample-application-db-changelog-job
  - mvn clean verify
cache:
  directories:
  - $HOME/.m2

services:
  - docker
addons:
  sonarcloud:
    organization: "nicolasospina-sanchez"
    token:
      secure: $SONARCLOUD_TOKEN # encrypted value of your token
