language: java

script:
  - mvn package -DskipTests
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t zerko/tp-cpe-travis:http-api-server sample-application-http-api-server
  - docker build -t zerko/tp-cpe-travis:db-changelog sample-application-db-changelog-job

cache:
  directories:
  - $HOME/.m2

services:
  - docker
